/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chatapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane; // Thư viện để hiện thông báo
import javax.swing.table.DefaultTableModel; // Thư viện để quản lý dữ liệu bảng
/**
 *
 * @author Admin
 */
public class AdminForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminForm.class.getName());

    /**
     * Creates new form AdminForm
     */
    public AdminForm() {

    initComponents();
    loadData(); // Load dữ liệu lần đầu khi mở form
    
    // THÊM ĐOẠN NÀY: Cứ mỗi 1500ms (1,5giây) sẽ tự gọi lại hàm loadData
    new javax.swing.Timer(1500, e -> {
        // Chỉ load lại nếu người dùng không đang chọn dòng nào để tránh bị nhảy bảng khi đang sửa
        if (tblNguoiDung.getSelectedRow() == -1) {
            loadData(); 
        }
    }).start();

    }
public void loadData() {
    // Lấy model của bảng tblNguoiDung bạn đã tạo
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblNguoiDung.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ trên bảng

    try (java.sql.Connection cn = DBConnect.getConnection()) {
        // Câu lệnh SQL lấy danh sách User (LoaiTaiKhoan = 0)
        String sql = "SELECT TenDangNhap, ThoiGianSuDung, HoTen, TrangThaiHoatDong FROM TaiKhoan WHERE LoaiTaiKhoan = 0";
        java.sql.Statement st = cn.createStatement();
        java.sql.ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            // Thêm từng dòng dữ liệu vào bảng
            model.addRow(new Object[]{
                rs.getString("TenDangNhap"),
                rs.getInt("ThoiGianSuDung"),
                rs.getString("HoTen"),
                rs.getString("TrangThaiHoatDong")
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguoiDung = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblNguoiDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNguoiDungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNguoiDung);

        jLabel1.setText("Tên đăng nhập:");

        jLabel2.setText("Thời gian sử dụng:");

        jLabel3.setText("Họ và tên:");

        txtHoTen.addActionListener(this::txtHoTenActionPerformed);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);

        btnSua.setText("Sửa");
        btnSua.addActionListener(this::btnSuaActionPerformed);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(this::btnXoaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(txtTime)
                            .addComponent(txtHoTen))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(btnSua)
                        .addGap(63, 63, 63)
                        .addComponent(btnXoa)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTimKiem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
                                      
    int row = tblNguoiDung.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xóa!");
        return;
    }
    
    String user = tblNguoiDung.getValueAt(row, 0).toString();
    int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa tài khoản " + user + "?", "Xác nhận", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        try (Connection cn = DBConnect.getConnection()) {
            PreparedStatement pst = cn.prepareStatement("DELETE FROM TaiKhoan WHERE TenDangNhap=?");
            pst.setString(1, user);
            pst.executeUpdate();
            loadData();
            JOptionPane.showMessageDialog(this, "Đã xóa tài khoản!");
        } catch (Exception e) { e.printStackTrace(); }
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
                                     
    String user = txtTenDangNhap.getText();
    String name = txtHoTen.getText();
    String time = txtTime.getText();

    if (user.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản từ bảng!");
        return;
    }

    try (Connection cn = DBConnect.getConnection()) {
        String sql = "UPDATE TaiKhoan SET HoTen = ?, ThoiGianSuDung = ? WHERE TenDangNhap = ?";
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, name);
        pst.setString(2, time);
        pst.setString(3, user);

        if (pst.executeUpdate() > 0) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            loadData();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
    }
      // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
                                           
    // Lấy dữ liệu từ các ô nhập liệu bên phải
    String user = txtTenDangNhap.getText().trim();
    String name = txtHoTen.getText().trim();
    
    // Lấy model của bảng để cập nhật lại dữ liệu hiển thị
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblNguoiDung.getModel();
    model.setRowCount(0); 

    try (java.sql.Connection cn = DBConnect.getConnection()) {
        // Câu lệnh SQL tìm kiếm gần đúng (LIKE) theo tên đăng nhập hoặc họ tên
        // Chỉ tìm những tài khoản là User (LoaiTaiKhoan = 0)
        String sql = "SELECT TenDangNhap, ThoiGianSuDung, HoTen, TrangThaiHoatDong FROM TaiKhoan "
                   + "WHERE (TenDangNhap LIKE ? AND HoTen LIKE ?) AND LoaiTaiKhoan = 0";
        
        java.sql.PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, "%" + user + "%");
        pst.setString(2, "%" + name + "%");
        
        java.sql.ResultSet rs = pst.executeQuery();
        
        // Kiểm tra xem có dữ liệu trả về không
        if (!rs.isBeforeFirst()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy người dùng phù hợp!");
            loadData(); // Nếu không thấy thì hiện lại toàn bộ danh sách
            return;
        }

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("TenDangNhap"),
                rs.getInt("ThoiGianSuDung"),
                rs.getString("HoTen"),
                rs.getString("TrangThaiHoatDong")
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblNguoiDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguoiDungMouseClicked
int row = tblNguoiDung.getSelectedRow(); // Lay dong dang duoc chon
    
    // Do du lieu tu bang vao cac o TextField
    txtTenDangNhap.setText(tblNguoiDung.getValueAt(row, 0).toString());
    txtTime.setText(tblNguoiDung.getValueAt(row, 1).toString());
    txtHoTen.setText(tblNguoiDung.getValueAt(row, 2).toString());
    
    // Luu y: Password thuong khong hien tren bang, ban co the tu nhap moi de sua        // TODO add your handling code here:
    }//GEN-LAST:event_tblNguoiDungMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminForm().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNguoiDung;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtTenDangNhap;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
