/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chatapp;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MainChatForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainChatForm.class.getName());

    /**
     * Creates new form MainChatForm
     */
    
    private int secondCounter = 0;
    public MainChatForm() {

    initComponents();
    loadDanhSachNguoiDung();
    
    new javax.swing.Timer(1000, e -> {
    loadTinNhan(); // Vẫn load tin nhắn mỗi giây

    // Xử lý đếm thời gian sử dụng
    secondCounter++;
    if (secondCounter >= 60) { // Đủ 60 giây (1 phút)
        updateUsageTime();      // Gọi hàm cập nhật SQL
        secondCounter = 0;      // Reset biến đếm
    }
}).start();
    }
private void updateUsageTime() {
    try (java.sql.Connection cn = DBConnect.getConnection()) {
        String sql = "UPDATE TaiKhoan SET ThoiGianSuDung = ThoiGianSuDung + 1 WHERE TenDangNhap = ?";
        java.sql.PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, LoginForm.currentUser); // Cập nhật cho đúng người đang dùng
        pst.executeUpdate();
    } catch (Exception e) { e.printStackTrace(); }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listBanBe = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnGui = new javax.swing.JButton();
        txtNhapTin = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaNoiDungChat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Tìm kiếm:");

        txtTimKiem.addActionListener(this::txtTimKiemActionPerformed);

        listBanBe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listBanBe);

        jLabel2.setText("Nhập tin nhắn:");

        btnGui.setText("Gửi");
        btnGui.addActionListener(this::btnGuiActionPerformed);

        txtNhapTin.addActionListener(this::txtNhapTinActionPerformed);

        areaNoiDungChat.setEditable(false);
        areaNoiDungChat.setColumns(20);
        areaNoiDungChat.setRows(5);
        jScrollPane2.setViewportView(areaNoiDungChat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNhapTin, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnGui)
                                .addGap(92, 92, 92)))
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNhapTin, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(46, 46, 46)
                        .addComponent(btnGui)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNhapTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhapTinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhapTinActionPerformed

    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
                                      
    String noiDung = txtNhapTin.getText().trim();
    String nguoiNhan = listBanBe.getSelectedValue();

    if (nguoiNhan == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một người để nhắn tin!");
        return;
    }
    if (noiDung.isEmpty()) return;

    try (java.sql.Connection cn = DBConnect.getConnection()) {
        String sql = "INSERT INTO TinNhan (NguoiGui, NguoiNhan, NoiDung) VALUES (?, ?, ?)";
        java.sql.PreparedStatement pst = cn.prepareStatement(sql);
        
        pst.setString(1, LoginForm.currentUser); // Lấy từ biến static ở LoginForm
        pst.setString(2, nguoiNhan); 
        pst.setString(3, noiDung);
        
        pst.executeUpdate();
        txtNhapTin.setText(""); 
        loadTinNhan(); // Cập nhật ngay lập tức khung chat
    } catch (Exception e) {
        e.printStackTrace();
    }

    }//GEN-LAST:event_btnGuiActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
                                         
    String search = txtTimKiem.getText().trim();
    DefaultListModel<String> model = new DefaultListModel<>();
    try (java.sql.Connection cn = DBConnect.getConnection()) {
        String sql = "SELECT TenDangNhap FROM TaiKhoan WHERE TenDangNhap LIKE ? AND LoaiTaiKhoan = 0 AND TenDangNhap != ?";
        java.sql.PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, "%" + search + "%");
        pst.setString(2, LoginForm.currentUser);
        java.sql.ResultSet rs = pst.executeQuery();
        while (rs.next()) {
            model.addElement(rs.getString("TenDangNhap"));
        }
        listBanBe.setModel(model);
    } catch (Exception e) { e.printStackTrace(); }

    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try (java.sql.Connection cn = DBConnect.getConnection()) {
    String sql = "UPDATE TaiKhoan SET TrangThaiHoatDong = N'Ngoại tuyến' WHERE TenDangNhap = ?";
    java.sql.PreparedStatement pst = cn.prepareStatement(sql);
    pst.setString(1, LoginForm.currentUser);
    pst.executeUpdate();
        } catch (Exception e) { e.printStackTrace(); }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainChatForm().setVisible(true));
    }
public void loadTinNhan() {
    String nguoiNhan = listBanBe.getSelectedValue();
    if (nguoiNhan == null) return;

    try (java.sql.Connection cn = DBConnect.getConnection()) {
        String sql = "SELECT NguoiGui, NoiDung FROM TinNhan WHERE "
                   + "(NguoiGui = ? AND NguoiNhan = ?) OR (NguoiGui = ? AND NguoiNhan = ?) "
                   + "ORDER BY ThoiGian ASC";
        
        java.sql.PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, LoginForm.currentUser);
        pst.setString(2, nguoiNhan);
        pst.setString(3, nguoiNhan);
        pst.setString(4, LoginForm.currentUser);
        
        java.sql.ResultSet rs = pst.executeQuery();
        StringBuilder sb = new StringBuilder();
        while (rs.next()) {
            String gui = rs.getString("NguoiGui");
            String nd = rs.getString("NoiDung");
            // Đánh dấu "Bạn: " cho dễ nhìn
            if (gui.equals(LoginForm.currentUser)) sb.append("Bạn: ").append(nd).append("\n");
            else sb.append(gui).append(": ").append(nd).append("\n");
        }
        areaNoiDungChat.setText(sb.toString());
    } catch (Exception e) {
        // Tránh in lỗi liên tục khi Timer chạy
    }
}
public void loadDanhSachNguoiDung() {
    javax.swing.DefaultListModel<String> model = new javax.swing.DefaultListModel<>();
    try (java.sql.Connection cn = DBConnect.getConnection()) { // Sử dụng getConnection() khớp với file DBConnect của bạn
        // Lấy tất cả người dùng thường (LoaiTaiKhoan = 0), trừ chính mình ra
        String sql = "SELECT TenDangNhap FROM TaiKhoan WHERE LoaiTaiKhoan = 0 AND TenDangNhap != ?";
        java.sql.PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, LoginForm.currentUser); 
        java.sql.ResultSet rs = pst.executeQuery();
        
        while (rs.next()) {
            model.addElement(rs.getString("TenDangNhap"));
        }
        listBanBe.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaNoiDungChat;
    private javax.swing.JButton btnGui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listBanBe;
    private javax.swing.JTextField txtNhapTin;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}

